require'configs.nvim-lsp'
require'configs.saga'
require'configs.completion'
require'configs.headerguard'
require'configs.nvim-tree'
require'configs.kommentary'
require'configs.vim-svelte'
require'configs.dashboard'
require'configs.gitgutter'
require'configs.polyglot'
require'configs.nvim-treesitter'
require'configs.latex-unicoder'
require'configs.yankhighlight'
require'configs.highlight'
-- require'configs.neovide'
require'configs.indentline'
require'configs.telescope'
require'configs.nvim-dap'
