#! /usr/bin/sh

# AUTOSTART
xsetroot -cursor_name left_ptr & # default cursor
udiskie & # usb mounting
sxhkd & # keybindings
picom -bfc # compositor
bg=$(xrdb -query | awk -v reso="background" '$1~reso{print $2;exit}')
fg=$(xrdb -query | awk -v reso="foreground" '$1~reso{print $2;exit}')
dunst -lb "$bg" -nb "$bg" -cb "$bg" -lf "$fg" -bf "$fg" -cf "$fg" -nf "$fg" -frame_color "$fg" & # notifications
$HOME/.config/polybar/launch.sh # polybar

# WALLPAPER (chosen randomly at startup)
multilockscreen --update ~/Pictures/Backgrounds
multilockscreen --wall
xss-lock -l -- multilockscreen --lock blur &

# MONITOR
if [[ $(hostname) == 'mihranLaptop' ]]; then
  bspc monitor eDP1 -d 0 1 2 3 4 5 6 7 8 9
fi

# BSPWM configuration
bspc config border_width         2
bspc config window_gap           8
bspc config top_padding          20
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# BSPWM colors
bspc config normal_border_color "$(xgetres darkgrey)"
bspc config focused_border_color "$(xgetres lightgrey)"
bspc config presel_feedback_color "$(xgetres darkgrey)"
