#! /usr/bin/sh

# AUTOSTART
xsetroot -cursor_name left_ptr & # default cursor
udiskie & # usb mounting
sxhkd & # keybindings
picom -bfc # compositor
#caffeine &
bg=$(xgetres background)
fg=$(xgetres foreground)
dunst -lb "$bg" -nb "$bg" -cb "$bg" -lf "$fg" -bf "$fg" -cf "$fg" -nf "$fg" -frame_color "$fg" &
$HOME/.config/polybar/launch.sh & # polybar

# MONITOR
if [[ "$(hostname)" == 'mihranLaptop' ]]; then
  #conky -c ~/.config/conky/thinkpadIMG.conf &
  #conky &
  bspc monitor $(bspc query --monitors | head) -d 0 1 2 3 4 5 6 7 8 9
  # WALLPAPER (chosen randomly at startup)
  ~/scripts/random-wallpaper
  # LightDM Lockscreen
  light-locker --lock-on-suspend &
elif [[ "$(hostname)" == 'mihranDesktop' ]]; then
  echo "works"
  bspc monitor HDMI-A-0 -d 0 1 2 3 4
  bspc monitor DVI-D-0 -d 5 6 7 8 9
  ds4drv --hidraw --daemon
  # WALLPAPER (chosen randomly at startup)
  ~/scripts/random-wallpaper
  # LightDM Lockscreen
  light-locker --lock-on-suspend &
  qjackctl -s &
fi


# BSPWM configuration
bspc config border_width         2
bspc config window_gap           8
bspc config top_padding          20
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# BSPWM colors
bspc config normal_border_color "$(xgetres darkgrey)"
bspc config focused_border_color "$(xgetres blue)"
bspc config presel_feedback_color "$(xgetres darkgrey)"

# Rules
[ -f ~/.config/bspwm/rules ] && source ~/.config/bspwm/rules
