#!/bin/sh

CAFFEINE_STATE_FILE=/tmp/caffeine_state
CAFFEINE=$(cat $CAFFEINE_STATE_FILE || (echo "OFF" > $CAFFEINE_STATE_FILE; echo "OFF"))

show() {
  [[ $CAFFEINE == "ON" ]] && echo "%{A1:~/scripts/caffeine-module toggle:}%{F$(xgetres foreground)} %{F-}%{A}" || echo %{A1:~/scripts/caffeine-module toggle:}%{F$(xgetres darkgrey)} %{F-}%{A}
}


toggle() {
  if [[ $CAFFEINE == "OFF" ]] 
  then
    echo "ON" > $CAFFEINE_STATE_FILE
    xset s off -dpms
  else
    echo "OFF" > $CAFFEINE_STATE_FILE
    xset s on dpms
  fi
}

case "$1" in
  t|toggle)
    toggle
    ;;
  s|show)
    show
    ;;
esac
