#! /usr/bin/bash

cd $HOME/Pictures/Backgrounds

ranger --choosefile=chosenpic

pic=$(cat chosenpic)

rm -f chosenpic

multilockscreen --update $pic
multilockscreen --wall

dunstify "Wallpaper Updated!"
