#!/bin/bash

# KILL AUTOSTARTED PROCESSES
killall xsetroot
killall udiskie
killall sxhkd
killall picom
killall caffeine
killall dunst
killall xss-lock
killall conky

# KILL ALL WINDOWS
for window_id in $(bspc query -W); do
  bspc window $window_id -c
done

bspc quit
