#!/bin/bash

DUNST_STATE_FILE=/tmp/dunst_state
DUNST_STATE=$(sed '1q;d' $DUNST_STATE_FILE)
SNOOZE_TIME=$(sed '2q;d' $DUNST_STATE_FILE)

COLOR_OFF=`xgetres darkgrey`
COLOR_ON=`xgetres foreground`

show() {
  output=""
  if [[ $DUNST_STATE == "" ]]
  then
    echo "RUNNING" >> $DUNST_STATE_FILE
    echo "NA" >> $DUNST_STATE_FILE
  fi
  if [[ $DUNST_STATE == "PAUSED" ]]
  then
    output="%{F$COLOR_ON}ﮖ %{F-}"
  else
    output="%{F$COLOR_OFF}ﮖ %{F-}"
  fi
  if [[ $SNOOZE_TIME != 'NA' ]]
  then
    output+=" %{T1}$SNOOZE_TIME%{T-}"
  fi
  echo "%{A1:~/scripts/dunst-snooze -m:}$output%{A} "
}

dunst_resume() {
  dunstctl set-paused false
  sed -i '1s/.*/RUNNING/' $DUNST_STATE_FILE
  sed -i '2s/.*/NA/' $DUNST_STATE_FILE
}

dunst_pause() {
  dunstctl set-paused true
  sed -i '1s/.*/PAUSED/' $DUNST_STATE_FILE
  sed -i "2s/.*/$1/" $DUNST_STATE_FILE
}

toggle() {
  [[ $DUNST_STATE == "PAUSED" ]] && dunst_resume || dunst_pause 'NA'
}

delayed_resume() {
  dunst_pause $1
  sleep $1 || return
  if [[ `sed '2q;d' $DUNST_STATE_FILE` != 'NA' ]]
  then
    notify-send "DUNST_COMMAND_RESUME"
    sed -i '1s/.*/RUNNING/' $DUNST_STATE_FILE
    sed -i '2s/.*/NA/' $DUNST_STATE_FILE
  fi
}

start_snooze() {
  menu=`echo "Until Turned Off|15 minutes|30 minutes|45 minutes|60 minutes|90 minutes|2 hours|3 hours|4 hours|5 hours|6 hours|Cancel" | rofi -lines 6 -columns 2 -sep "|" -dmenu -i -p "Snooze for"`
  length='0m'
  case $menu in
    'Until Turned Off')
      toggle
      return
      ;;
    '15 minutes')
      length='15m' ;;
    '30 minutes')
      length='30m' ;;
    '45 minutes')
      length='45m' ;;
    '60 minutes')
      length='1h' ;;
    '90 minutes')
      length='1.5h';;
    '2 hours')
      length='2h';;
    '3 hours')
      length='3h';;
    '4 hours')
      length='4h';;
    '5 hours')
      length='5h';;
    '6 hours')
      length='6h';;
    'Cancel'|'')
      return;;
    *)
      length=$menu;;
  esac
  delayed_resume $length &
}

snoozing_menu() {
  menu=`echo 'Turn Snooze Off|Cancel' | rofi -sep "|" -dmenu -i`
  case $menu in
    *'Off')
      toggle
  esac
}

case $1 in
  "-t" | "--toggle" )
    toggle;;
  "-m" | "--menu" )
    [[ $DUNST_STATE == "PAUSED" ]] && snoozing_menu || start_snooze;;
  *)
    show;;
esac
