#!/usr/bin/bash
case "$1" in
  devices)
    echo $(qdbus --literal org.kde.kdeconnect /modules/kdeconnect org.kde.kdeconnect.daemon.devices);;
  
  name|type|isReachable|isTrusted|hasPairingRequests|requestPair|unpair|acceptPairing|rejectPairing)
    echo $(qdbus org.kde.kdeconnect "/modules/kdeconnect/devices/$2" "org.kde.kdeconnect.device.$1");;
  
  charge|isCharging)
    echo $(qdbus org.kde.kdeconnect "/modules/kdeconnect/devices/$2/battery" "org.kde.kdeconnect.device.battery.$1");;
    
  ping)
    qdbus org.kde.kdeconnect "/modules/kdeconnect/devices/$2/ping" org.kde.kdeconnect.device.ping.sendPing;;

  sendFile)
    qdbus org.kde.kdeconnect "/modules/kdeconnect/devices/$2/share" org.kde.kdeconnect.device.share.shareUrl "file://$(zenity --file-selection)";;
  
  browseFiles)
    if "$(qdbus --literal org.kde.kdeconnect "/modules/kdeconnect/devices/$2/sftp" org.kde.kdeconnect.device.sftp.isMounted)" == "false";
    then
      qdbus org.kde.kdeconnect "/modules/kdeconnect/devices/$2/sftp" org.kde.kdeconnect.device.sftp.mount
    fi
    qdbus org.kde.kdeconnect "/modules/kdeconnect/devices/$2/sftp" org.kde.kdeconnect.device.sftp.startBrowsing;;

  ring)
    qdbus org.kde.kdeconnect "/modules/kdeconnect/devices/$2/findmyphone" org.kde.kdeconnect.device.findmyphone.ring;;
    
  *)
    echo "";;
esac
