#!/usr/bin/env bash

# CONFIGURATION
LOCATION=0
YOFFSET=0
XOFFSET=0
WIDTH=12
WIDTH_WIDE=24

# Color Settings of Icon shown in Polybar
COLOR_DISCONNECTED="$(xgetres darkgrey)"       # Device Disconnected
COLOR_NEWDEVICE="$(xgetres yellow)"          # New Device
COLOR_BATTERY="$(xgetres foreground)"      # Battery >= 90
COLOR_BATTERY_LOW="$(xgetres background)"        # Battery <  50

# Icons shown in Polybar
ICON_SMARTPHONE=''
ICON_TABLET=''
SEPERATOR='|'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
FILENAME=`basename "$0"`

wrapper=$DIR/kdeconnect_qdbus

show_devices (){
    IFS=$','
    devices=""
    devicelist=$($wrapper devices)
    if [ "$devicelist" = "{}" ]
    then
            echo ""
    else
    for device in $devicelist; do
        deviceid=$(echo "$device" | awk -F'["|"]' '{print $2}')
        devicename=$($wrapper name $deviceid)
        devicetype=$($wrapper type $deviceid)
        isreach="$($wrapper isReachable $deviceid)"
        istrust="$($wrapper isTrusted $deviceid)"
        if [ "$isreach" = "true" ] && [ "$istrust" = "true" ]
        then
            battery="$($wrapper charge $deviceid)"
            charging="$($wrapper isCharging $deviceid)"
            icon=$(get_icon "$battery" "$devicetype" "$charging")
            devices+="%{A1:$DIR/$FILENAME -n '$devicename' -i $deviceid -b $battery -m:}$icon%{A}$SEPERATOR"
        elif [ "$isreach" = "false" ] && [ "$istrust" = "true" ]
        then
            devices+="$(get_icon -1 "$devicetype")$SEPERATOR"
        else
          haspairing="$($wrapper hasPairingRequests $deviceid)"
            if [ "$haspairing" = "true" ]
            then
                show_pmenu2 "$devicename" "$deviceid"
            fi
            icon=$(get_icon -2 "$devicetype")
            devices+="%{A1:$DIR/$FILENAME -n $devicename -i $deviceid -p:}$icon%{A}$SEPERATOR"

        fi
    done
    echo "${devices::-1}"
    fi
}

show_menu () {
    menu="$(rofi -sep "|" -dmenu -i -p "$DEV_NAME" -location $LOCATION -yoffset $YOFFSET -xoffset $XOFFSET -hide-scrollbar -line-padding 4 -padding 20 -lines 6 <<< "Battery: $DEV_BATTERY%|Ping|Find Device|Send File|Browse Files|Unpair")"
                case "$menu" in
                    *'Ping') $wrapper ping $DEV_ID;;
                    *'Find Device') $wrapper ring $DEV_ID;;
                    *'Send File') $wrapper sendFile $DEV_ID;;
                    *'Browse Files') $wrapper browseFiles $DEV_ID;;
                    *'Unpair' ) $wrapper unpair $DEV_ID;;
                esac
}

show_pmenu () {
    menu="$(rofi -sep "|" -dmenu -i -p "$DEV_NAME" -location $LOCATION -yoffset $YOFFSET -xoffset $XOFFSET -hide-scrollbar -line-padding 1 -padding 20 -lines 1<<<"Pair Device")"
                case "$menu" in
                    *'Pair Device') $wrapper requestPair $DEV_ID
                esac
}

show_pmenu2 () {
    menu="$(rofi -sep "|" -dmenu -i -p "$1 has sent a pairing request" -location $LOCATION -yoffset $YOFFSET -xoffset $XOFFSET -hide-scrollbar -line-padding 4 -padding 20 -lines 2 <<< "Accept|Reject")"
                case "$menu" in
                    *'Accept') $wrapper acceptPairing $DEV_ID;;
                    *) $wrapper rejectPairing $DEV_ID;;
                esac
}

get_icon () {
    if [ "$3" = "true" ]
    then
        charging="+"
    else
        charging=""
    fi
    if [ "$2" = "tablet" ]
    then
        icon=$ICON_TABLET
    else
        icon=$ICON_SMARTPHONE
    fi
    case $1 in
    "-1")     ICON="%{F$COLOR_DISCONNECTED}$icon%{F-}" ;;
    "-2")     ICON="%{F$COLOR_NEWDEVICE}$icon%{F-}" ;;
    100)      ICON="%{F$COLOR_BATTERY}$icon $1%%{F-}";;
    3*|4*|5*|6*|7*|8*|9*)     ICON="%{F$COLOR_BATTERY}$icon $charging$1%%{F-}" ;;
    *)      ICON="%{F$COLOR_BATTERY_LOW}$icon $charging$1%%{F-}" ;;
    esac
    echo $ICON
}

unset DEV_ID DEV_NAME DEV_BATTERY
while getopts 'di:n:b:mp' c
do
    # shellcheck disable=SC2220
    case $c in
        d) show_devices ;;
        i) DEV_ID=$OPTARG ;;
        n) DEV_NAME=$OPTARG ;;
        b) DEV_BATTERY=$OPTARG ;;
        m) show_menu  ;;
        p) show_pmenu ;;
    esac
done
