#! /usr/bin/bash

set -e

STATE_FILE=/tmp/systray_state

[[ -s $STATE_FILE ]] || echo "HIDDEN" >$STATE_FILE

STATE=`cat $STATE_FILE`

if [[ $1 == "show" ]];
then
  if [[ $STATE == "HIDDEN" ]]
  then
    COLOR_OFF=`xgetres darkgrey`
    echo "%{F$COLOR_OFF}%{F-} "
  else
    COLOR_ON=`xgetres foreground`
    echo "%{F$COLOR_ON}%{F-} "
  fi
  exit
fi

if [[ $STATE == "HIDDEN" ]];
then
  polybar-msg cmd show && echo "VISIBLE" >$STATE_FILE && bspc config top_padding 40
else
  polybar-msg cmd hide && echo "HIDDEN" >$STATE_FILE && bspc config top_padding 20
fi
