#!/bin/bash

theme_file="$HOME/.config/kitty/mytheme.conf"

resources="foreground background color0 color8 color1 color9 color2 color10 color3 color11 color4 color12 color5 color13 color6 color14 color7 color15"

for res in $resources; do
  value=$(xrdb -query | awk -v reso=$res '$1~reso{print $2;exit}')
  sed -i --follow-symlinks "/\b$res\b/c\\$res $value" "$theme_file"
  echo "$res  $value"
done 
